[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "renamer"
version = "0.5.0"
dependencies = [
    "click",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
renamer = "renamer.__main__:cli"